[general]
library_name = "libcholmod"
library_names = { "cs.h" = "libcxsparse"}

use_julia_native_enum_type = true
use_deterministic_symbol = true
auto_mutability = true

output_ignorelist = [
    # Clang.jl cannot handle these macro correctly, skip for now.
    "SuiteSparse_long_id",
]

[codegen]
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"

functionlike_macro_includelist = [
    "SUITESPARSE_VER_CODE",
]